version: '0.1.0-ci.{build}'
init:
  - git config --global core.autocrlf input
branches:
  only:
    - main
build_script:
  - build.cmd
before_build:
  - choco install dotnet-sdk --version 8.0.100
clone_depth: 1
test: off
